
export const POSTDATA = {
  POSTDATA_URL: "POSTDATA_URL",
  POSTDATA_RESET: "POSTDATA_RESET",
  POSTDATA_SUCCESS: "POSTDATA_SUCCESS",
  POSTDATA_FAILURE: "POSTDATA_FAILURE",
};


export const GETDETAIL = {
  GET_DATA_URL: "GET_DATA_URL",
  GET_DATA_RESET: "GET_DATA_RESET",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",
};
